name = "bloxhelp"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "bloxhelp-db"
database_id = "26771ad8-a30c-4cda-a8f2-e56fab260209"
